/* Makes the same person's DNA in each provider's file format, reads every file with
   the real parser (in Node), and checks the results match the 23andMe original.
   Run from the repository root: node tests/formats.js */
const fs = require('fs'), path = require('path'), zlib = require('zlib'), { execFileSync } = require('child_process');
const root = path.join(__dirname, '..'), out = path.join(root, 'shots', 'formats');
fs.mkdirSync(out, { recursive: true });
const load = f => fs.readFileSync(path.join(root, f), 'utf8');
global.self = global;
new Function(load('deps/fflate-0.8.3/index.js'))();
eval(load('src/data.js') + load('src/ref.js') + load('src/b38.js') + load('src/anc.js') + load('src/worker.js') +
  ';global.SNP_DEF=SNP_DEF;global.CURATED_IDS=CURATED_IDS;global.CURATED_POS=CURATED_POS;global.REF_PANEL=REF_PANEL;global.REF_MT=REF_MT;global.REF_Y=REF_Y;global.REF_B38=REF_B38;global.locusAnc=locusAnc;global.locusWorker=locusWorker');

function engine() {
  const w = {}; let done;
  locusWorker(w, m => { if (m.type === 'done' || m.type === 'error') done(m); });
  w.onmessage({ data: { type: 'ref', ref: { P: REF_PANEL, MT: REF_MT, Y: REF_Y, B38: REF_B38 }, curated: { pos: CURATED_POS } } });
  return (file, name) => new Promise(r => { done = r; w.onmessage({ data: { type: 'parse', id: 1, file: new File([fs.readFileSync(file)], name || path.basename(file)), curated: CURATED_IDS, coords: CURATED_POS, heritage: true, keep: false } }); });
}

// One person: the heritage test file, plus the curated markers and X from the other test file.
const rd = f => load('tests/files/' + f).split('\n').filter(l => l && l[0] !== '#').map(l => l.split('\t'));
const her = rd('genome_Full_her.txt'), me = rd('genome_Full_me.txt');
const cur = new Set(CURATED_IDS), seen = new Set(her.map(r => r[0]));
const base = her.concat(me.filter(r => !seen.has(r[0]) && (cur.has(r[0]) || r[1] === 'X')));
const order = c => c === 'X' ? 23 : c === 'Y' ? 24 : c === 'MT' ? 25 : +c;
base.sort((a, b) => order(a[1]) - order(b[1]) || a[2] - b[2]);

// Every site the parser knows, with GRCh38 positions and reference letters.
const A = locusAnc(), U = A.unpackPanel(REF_PANEL);
const runs = s => { const o = []; for (const t of s.split(',')) { const [v, n] = t.split('*'); for (let k = 0; k < (+n || 1); k++) o.push(v === 'x' ? null : +v); } return o; };
const off = runs(REF_B38.panel), site = new Map();
for (let i = 0; i < U.n; i++) site.set(U.ids[i], { p38: off[i] == null ? 0 : U.pos[i] + off[i], ref: U.ref[i], alt: U.alt[i] });
for (const id in REF_B38.cur) if (!site.has(id)) site.set(id, { p38: REF_B38.cur[id][0], ref: REF_B38.cur[id][1] });
const yo = runs(REF_B38.y); let yp = 0; const ysite = new Map();
REF_Y.pos.split(',').forEach((d, i) => { yp += +d; if (yo[i] != null) ysite.set(yp, { p38: yp + yo[i], anc: REF_Y.alle[2 * i], der: REF_Y.alle[2 * i + 1] }); });

const W = (name, text) => { fs.writeFileSync(path.join(out, name), text); return path.join(out, name); };
const gz = (name, parts) => { fs.writeFileSync(path.join(out, name), Buffer.concat(parts.map(p => zlib.gzipSync(p)))); return path.join(out, name); };
const zip = (name, inner, text) => { const t = W(inner, text); execFileSync('python3', ['-c', `import zipfile,sys;z=zipfile.ZipFile(sys.argv[1],'w',zipfile.ZIP_DEFLATED);z.write(sys.argv[2],sys.argv[3]);z.close()`, path.join(out, name), t, inner]); fs.unlinkSync(t); return path.join(out, name); };
const chunks = (text, n) => { const b = Buffer.from(text), o = []; for (let i = 0; i < b.length; i += n) o.push(b.subarray(i, i + n)); return o; };
const split2 = g => g.length === 2 ? [g[0], g[1]] : g.length === 1 ? [g, g] : ['0', '0'];

const files = {};
files['23andMe (control)'] = W('genome_Full_23andme.txt', '# This data file generated by 23andMe at: test\n# rsid\tchromosome\tposition\tgenotype\n' + base.map(r => r.join('\t')).join('\n') + '\n');
files['AncestryDNA (zip)'] = zip('AncestryDNA.zip', 'AncestryDNA.txt', '#AncestryDNA raw data download\n#This file was generated by AncestryDNA at: 2024\n#Genetic data is provided below as five TAB delimited columns.\nrsid\tchromosome\tposition\tallele1\tallele2\n' +
  base.map(r => { const c = { X: '23', Y: '24', MT: '26' }[r[1]] || r[1], [a, b] = /^[ACGT]{1,2}$/.test(r[3]) ? split2(r[3]) : ['0', '0']; return [r[0], c, r[2], a, b].join('\t'); }).join('\n') + '\n');
files['MyHeritage (gzip)'] = gz('MyHeritage_raw_dna_data.csv.gz', ['##fileformat=MyHeritage\n##format=MHv1.0\n##chip=GSA\n##reference=build37\nRSID,CHROMOSOME,POSITION,RESULT\n' + base.map(r => r.map(x => `"${x}"`).join(',')).join('\n') + '\n']);
files['MyHeritage, extra quotes'] = W('myheritage_quotes.csv', '# MyHeritage, https://www.myheritage.com\nRSID,CHROMOSOME,POSITION,RESULT\n' + base.map(r => `"${r[0]}"",""${r[1]}"",""${r[2]}"",""${r[3]}"`).join('\n') + '\n');
const half = Math.floor(base.length / 2), ft = r => r.map(x => `"${x}"`).join(',');
files['FamilyTreeDNA (joined gzip)'] = gz('ftdna_Autosomal_o37_Results.csv.gz', ['RSID,CHROMOSOME,POSITION,RESULT\n' + base.slice(0, half).map(ft).join('\n') + '\n', 'RSID,CHROMOSOME,POSITION,RESULT\n' + base.slice(half).map(ft).join('\n') + '\n']);
files['Living DNA'] = W('livingdna.txt', '# Living DNA customer genotype data download file version: 1.0.1\n# Human Genome Reference Build 37 (GRCh37.p13)\n# rsid\tchromosome\tposition\tgenotype\n' + base.map(r => r.join('\t')).join('\n') + '\n');
files['Genes for Good (header in comment)'] = W('genesforgood.txt', '# Genes for Good\n#\n# rsid\tchromosome\tposition\tgenotype\n' + base.map(r => r.join('\t')).join('\n') + '\n');
files['Sano (allele_1 allele_2)'] = W('sano.txt', '# This file was derived from the corresponding VCF file to provide genetic\nrsid chromosome position allele_1 allele_2\n' + base.map(r => { const [a, b] = /^[ACGT]{1,2}$/.test(r[3]) ? split2(r[3]) : ['-', '-']; return [r[0], r[1], r[2], a, b].join(' '); }).join('\n') + '\n');
files['Illumina report (Plus strand)'] = W('FinalReport.txt', '[Header]\nGSGT Version\t2.0.4\nContent\t\tGSA-24v3-0_A1.bpm\n[Data]\nSNP Name\tSample ID\tAllele1 - Top\tAllele2 - Top\tAllele1 - Plus\tAllele2 - Plus\tChr\tPosition\tRsID\n' +
  base.map((r, i) => { const [a, b] = /^[ACGT]{1,2}$/.test(r[3]) ? split2(r[3]) : ['-', '-']; return [i % 2 ? 'GSA-' + r[0] : r[0], 'S1', 'A', 'B', a, b, r[1], r[2], i % 2 ? '.' : r[0]].join('\t'); }).join('\n') + '\n');
files['Codigo46 (no chromosome column)'] = W('codigo46.txt', '[Header]\nContent\t\tCODIGO46.bpm\n[Data]\nSample Name\tSNP Name\tAllele1 - Plus\tAllele2 - Plus\n' +
  base.map(r => { const [a, b] = /^[ACGT]{1,2}$/.test(r[3]) ? split2(r[3]) : ['-', '-']; return ['123', r[1] + ':' + r[2], a, b].join('\t'); }).join('\n') + '\n');
files['tellmeGen (chip names, not rsids)'] = W('tellmegen.txt', 'rsid\tChromosome\tposition\tgenotype\n' + base.map(r => [r[1] + ':' + r[2], r[1], r[2], r[3]].join('\t')).join('\n') + '\n');
files['23andMe on build 36'] = W('genome_build36.txt', '# This data file generated by 23andMe at: 2010\n# We are using reference human assembly build 36\n# rsid\tchromosome\tposition\tgenotype\n' + base.map(r => [r[0], r[1], r[1] === 'MT' ? r[2] : +r[2] + 1777, r[3]].join('\t')).join('\n') + '\n');

// VCFs. Array style: every site listed, GRCh37, rsids.
const vref = r => { const s = site.get(r[0]); if (s && s.ref) return s.ref; if (r[1] === 'MT') return REF_MT.ref[r[2] - 1]; const y = r[1] === 'Y' && ysite.get(+r[2]); if (y) return y.anc; return r[3][0]; };
const vcfRow = (chr, p, id, ref, g) => {
  if (!/^[ACGT]{1,2}$/.test(g)) return `${chr}\t${p}\t${id}\t${ref}\t.\t.\tPASS\t.\tGT\t${'./.'}`;
  const al = [ref]; const idx = [...g].map(a => { let k = al.indexOf(a); if (k < 0) { al.push(a); k = al.length - 1; } return k; });
  return `${chr}\t${p}\t${id}\t${ref}\t${al.slice(1).join(',') || '.'}\t50\tPASS\t.\tGT\t${idx.join('/')}`;
};
const C37 = '##contig=<ID=1,length=249250621>\n##contig=<ID=MT,length=16569>\n';
files['VCF from a chip (GRCh37)'] = W('array.vcf', '##fileformat=VCFv4.2\n##source=Example\n' + C37 + '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n' + base.map(r => vcfRow(r[1], r[2], r[0], vref(r), r[3])).join('\n') + '\n');

// Whole genome, GRCh38: only sites that differ from the reference, no rsids, many other variants, bgzip-style blocks.
const C38 = '##contig=<ID=chr1,length=248956422>\n##contig=<ID=chrM,length=16569>\n##reference=GRCh38\n';
const wgs = [], gv = [];
for (const r of base) {
  const c = r[1]; let p38 = 0, ref = '';
  if (c === 'MT') { p38 = +r[2]; ref = REF_MT.ref[p38 - 1]; }
  else if (c === 'Y') { const y = ysite.get(+r[2]), s = site.get(r[0]); if (s && s.p38 && s.ref) { p38 = s.p38; ref = s.ref; } else if (y) { p38 = y.p38; ref = y.anc; } else continue; }
  else { const s = site.get(r[0]); if (!s || !s.p38 || !s.ref) continue; p38 = s.p38; ref = s.ref; }
  if (!/^[ACGT]{1,2}$/.test(r[3])) continue;
  const g = c === 'X' || c === 'Y' || c === 'MT' ? r[3][0] : r[3];
  wgs.push([c, p38, g === ref || g === ref + ref ? null : vcfRow('chr' + (c === 'MT' ? 'M' : c), p38, '.', ref, g)]);
}
let seed = 7; const rnd = n => { seed = (seed * 1103515245 + 12345) % 2147483648; return seed % n; };
const taken = new Set(wgs.map(w => w[0] + ':' + w[1]));
for (let i = 0; i < 1100000; i++) { const c = String(1 + rnd(22)), p = 1e6 + rnd(9e7); if (taken.has(c + ':' + p)) continue; wgs.push([c, p, vcfRow('chr' + c, p, '.', 'ACGT'[rnd(4)], ['AC', 'GG', 'TA', 'CT'][rnd(4)]), 'filler']); }
wgs.sort((a, b) => order(a[0]) - order(b[0]) || a[1] - b[1]);
const H38 = '##fileformat=VCFv4.2\n##source=DeepVariant\n' + C38 + '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tNG1234\n';
files['Whole genome VCF (GRCh38, bgzip)'] = gz('NG1234.vcf.gz', chunks(H38 + wgs.filter(w => w[2]).map(w => w[2]).join('\n') + '\n', 65280));

// gVCF: reference blocks between the variants, on the sites we know about.
const tg = wgs.filter(w => !w[3]);
const byc = {}; for (const w of tg) (byc[w[0]] = byc[w[0]] || []).push(w);
const lines = [];
for (const c of Object.keys(byc).sort((a, b) => order(a) - order(b))) {
  let at = 1; const name = 'chr' + (c === 'MT' ? 'M' : c);
  for (const w of byc[c]) {
    if (w[1] > at) lines.push(`${name}\t${at}\t.\tN\t<NON_REF>\t.\t.\tEND=${w[1] - 1}\tGT:DP\t0/0:30`);
    if (w[2]) lines.push(w[2].replace(/\t(\S+)\t50\tPASS/, (m, a) => `\t${a === '.' ? '<NON_REF>' : a + ',<NON_REF>'}\t50\tPASS`));
    else lines.push(`${name}\t${w[1]}\t.\tN\t<NON_REF>\t.\t.\tEND=${w[1]}\tGT:DP\t${c === 'X' || c === 'Y' || c === 'MT' ? '0' : '0/0'}:30`);
    at = w[1] + 1;
  }
}
files['gVCF (GRCh38)'] = gz('sample.g.vcf.gz', chunks('##fileformat=VCFv4.2\n##GVCFBlock0-1=minGQ=0(inclusive),maxGQ=1(exclusive)\n' + C38 + '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1\n' + lines.join('\n') + '\n', 65280));

const errs = {
  'BAM file': [gz('reads.bam', [Buffer.from('BAM\x01' + 'x'.repeat(200))]), 'unsupported'],
  'Match list': [W('matches.csv', 'Full Name,Match Date,Shared cM\n' + 'A B,2024,30\n'.repeat(2000)), 'format'],
  'PDF': [W('report.pdf', '%PDF-1.4\n' + 'x'.repeat(5000)), 'unsupported']
};

(async () => {
  const run = engine(), ok = [], bad = [];
  const sum = r => ({ rows: r.rows, sex: r.sex, vendor: r.vendor, build: r.build, kind: r.kind, filled: r.filled,
    top: r.heritage && r.heritage.anc && !r.heritage.anc.tooFew ? r.heritage.anc.groups.slice(0, 3).map(g => g.id + ' ' + g.pct) : null,
    mt: r.heritage && r.heritage.mt && r.heritage.mt.hg, y: r.heritage && r.heritage.y && r.heritage.y.hg, genos: r.genos });
  let ctl = null;
  for (const [label, f] of Object.entries(files)) {
    const t0 = Date.now(), m = await run(f);
    if (m.type === 'error') { bad.push(`${label}: error ${m.code} ${m.why}`); console.log('✗', label, m.code, m.why); continue; }
    const s = sum(m.result);
    if (!ctl) ctl = s;
    const gd = Object.keys(ctl.genos).filter(k => { const a = ctl.genos[k], b = s.genos[k]; return a !== b && !(s.build === 36 && b === '--') && !(b && a && a[0] === b && a.length === 2 && a[0] === a[1]); });
    const diff = [];
    if (gd.length) diff.push('genotypes differ: ' + gd.slice(0, 6).map(k => `${k} ${ctl.genos[k]}→${s.genos[k]}`).join(', ') + (gd.length > 6 ? ` +${gd.length - 6}` : ''));
    if (JSON.stringify(s.top && s.top.map(x => x.split(' ')[0])) !== JSON.stringify(ctl.top && ctl.top.map(x => x.split(' ')[0]))) diff.push(`groups ${s.top} vs ${ctl.top}`);
    if (s.mt !== ctl.mt) diff.push(`mt ${s.mt} vs ${ctl.mt}`);
    if (s.y !== ctl.y && !(s.build === 36 && s.y === null)) diff.push(`y ${s.y} vs ${ctl.y}`);
    if (s.sex !== ctl.sex) diff.push(`sex ${s.sex}`);
    const line = `${label}: ${s.vendor || '-'} / ${s.kind} / build ${s.build} / ${s.rows} rows${s.filled ? ', ' + s.filled + ' filled' : ''} / ${s.sex} / ${s.top && s.top[0]} / mt ${s.mt} / y ${s.y} (${Date.now() - t0} ms)`;
    console.log(diff.length ? '✗' : '✓', line); diff.forEach(d => console.log('    ', d));
    (diff.length ? bad : ok).push(label);
  }
  for (const [label, [f, want]] of Object.entries(errs)) {
    const m = await run(f);
    const good = m.type === 'error' && m.code === want;
    console.log(good ? '✓' : '✗', `${label}: ${m.type} ${m.code || ''} ${m.kind || ''}`);
    (good ? ok : bad).push(label);
  }
  console.log(`\n${ok.length} passed, ${bad.length} failed`);
  process.exit(bad.length ? 1 : 0);
})();
