/* Checks the whole-genome features on simulated people: runs of homozygosity,
   relative matching (self, parent, sibling, half sibling, cousin, unrelated), and
   painting each copy of a phased file. Run from the repository root: node tests/genome.js */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const load = f => fs.readFileSync(path.join(root, f), 'utf8');
global.self = global;
new Function(load('deps/fflate-0.8.3/index.js'))();
eval(load('src/data.js') + load('src/ref.js') + load('src/b38.js') + load('src/anc.js') + load('src/worker.js') +
  ';global.CURATED_IDS=CURATED_IDS;global.CURATED_POS=CURATED_POS;global.REF_PANEL=REF_PANEL;global.REF_MT=REF_MT;global.REF_Y=REF_Y;global.REF_B38=REF_B38;global.locusAnc=locusAnc;global.locusWorker=locusWorker');

const w = {}; let done;
locusWorker(w, m => { if (m.type === 'done' || m.type === 'error') done(m); });
w.onmessage({ data: { type: 'ref', ref: { P: REF_PANEL, MT: REF_MT, Y: REF_Y, B38: REF_B38 }, curated: { pos: CURATED_POS } } });
const parse = (text, name, extra) => new Promise(r => { done = r; w.onmessage({ data: Object.assign({ type: 'parse', id: 1, file: new File([text], name), curated: CURATED_IDS, coords: CURATED_POS, heritage: false }, extra) }); });

let seed = 11; const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; };
const U = locusAnc().unpack(REF_PANEL), K = U.K;
const LEN = [249, 243, 198, 191, 181, 171, 159, 146, 141, 135, 135, 133, 115, 107, 102, 90, 81, 78, 59, 63, 48, 51];
// Sites: the reference panel plus evenly spread filler markers, like a 600k chip.
const sites = [];
for (let i = 0; i < U.n; i++) sites.push({ id: U.ids[i], c: U.chr[i], p: U.pos[i], ref: U.ref[i], alt: U.alt[i], f: k => U.F[i * K + k] });
for (let c = 1; c <= 22; c++) for (let k = 0; k < LEN[c - 1] * 220; k++) { const q = 0.05 + 0.9 * rnd(); sites.push({ id: `rs${900000000 + c * 1000000 + k}`, c, p: 1e5 + Math.floor(k * 1e6 / 220), ref: 'C', alt: 'T', f: () => q }); }
sites.sort((a, b) => a.c - b.c || a.p - b.p);
const grp = id => REF_PANEL.groups.findIndex(g => g.id === id);
const hap = (k) => sites.map(s => rnd() < s.f(k) ? 1 : 0);
const person = (k1, k2) => [hap(k1), hap(k2 == null ? k1 : k2)];
// A child gets one copy from each parent, with about one crossover every 100 Mb.
const gamete = P => { let cur = rnd() < 0.5 ? 0 : 1, lastC = 0; return sites.map((s, i) => { if (s.c !== lastC) { lastC = s.c; cur = rnd() < 0.5 ? 0 : 1; } else if (rnd() < (s.p - sites[i - 1].p) / 1e8) cur = 1 - cur; return P[cur][i]; }); };
const child = (A, B) => [gamete(A), gamete(B)];
const text = (P, phased) => '# This data file generated by 23andMe at: test\n# rsid\tchromosome\tposition\tgenotype\n' +
  sites.map((s, i) => { const a = P[0][i] ? s.alt : s.ref, b = P[1][i] ? s.alt : s.ref; return `${s.id}\t${s.c}\t${s.p}\t${phased ? a + '|' + b : a + b}`; }).join('\n') + '\n';

(async () => {
  const fails = []; const check = (ok, msg) => { console.log(ok ? 'PASS' : 'FAIL', msg); if (!ok) fails.push(msg); };
  const eu = grp('nwe');
  // 1. Runs of homozygosity: an outbred person, then one whose parents are first cousins (copy runs made identical).
  const out = person(eu);
  let r = (await parse(text(out), 'a.txt')).result.roh;
  check(r && !r.tooFew && r.f < 0.005, `outbred: F_ROH ${(r.f * 100).toFixed(2)}%, ${r.n} runs, het ${(r.het * 100).toFixed(1)}%`);
  const inb = person(eu); const runs = [[2, 40e6, 62e6], [7, 10e6, 24e6], [11, 70e6, 80e6], [15, 30e6, 33e6]];
  sites.forEach((s, i) => { if (runs.some(([c, a, b]) => s.c === c && s.p >= a && s.p <= b)) inb[1][i] = inb[0][i]; });
  r = (await parse(text(inb), 'b.txt')).result.roh;
  const found = runs.filter(([c, a, b]) => r.segs.some(sg => sg[0] === c && sg[1] <= a + 2e6 && sg[2] >= b - 2e6)).length;
  check(found === 4 && r.longMb > 40, `cousin parents: found ${found} of 4 planted runs, ${r.totalMb.toFixed(1)} Mb, F_ROH ${(r.f * 100).toFixed(2)}%, long ${r.longMb.toFixed(1)} Mb`);

  // 2. Relatives.
  const mom = person(eu), dad = person(eu), kid = child(mom, dad), kid2 = child(mom, dad);
  const other = person(eu), half = child(mom, other), aunt = child(person(eu), person(eu));
  const cousinA = child(child(mom, dad), person(eu)), cousinB = child(child(mom, dad), person(eu));
  const pairs = [['same', mom, mom], ['parent', mom, kid], ['sibling', kid, kid2], ['second', kid, half], ['third', cousinA, cousinB], ['none', mom, other]];
  for (const [want, A, B] of pairs) {
    await parse(text(A), 'a.txt', { keep: true });
    const c = (await parse(text(B), 'b.txt', { keep: false, compare: true })).result.compare;
    check(c.rel === want, `${want}: got ${c.rel}, kinship ${c.phi.toFixed(3)}, IBS0 ${(c.ibs0 * 100).toFixed(2)}%, ${c.n} markers`);
  }

  // 3. Phased painting: one copy African, the other European.
  const af = grp(REF_PANEL.groups.find(g => g.region === 'afr').id);
  const mix = [hap(af), hap(eu)];
  const ph = (await parse('# phased\n' + text(mix, true), 'phased_genotype.txt', { heritage: true })).result.heritage;
  const share = (cp, reg) => { let t = 0, a = 0; ph.paint.forEach(c => c[cp].forEach(s => { t += s.e - s.s; if (s.pop === reg) a += s.e - s.s; })); return a / t; };
  check(ph.phasedPaint && share(0, 'afr') > 0.85 && share(1, 'eu') > 0.85, `phased painting: copy 1 ${(share(0, 'afr') * 100).toFixed(0)}% African, copy 2 ${(share(1, 'eu') * 100).toFixed(0)}% European`);
  const un = (await parse(text(mix), 'genome_Full.txt', { heritage: true })).result.heritage;
  const segs = un.paint.reduce((t, c) => t + c[0].length + c[1].length, 0);
  check(!un.phasedPaint && segs < 120, `unphased painting stays smooth: ${segs} segments over 22 chromosomes`);
  // Files for the browser test (tests/realtest.js).
  const dir = path.join(root, 'shots', 'genome'); fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'genome_cousins.txt'), text(inb)); fs.writeFileSync(path.join(dir, 'genome_mom.txt'), text(mom));
  fs.writeFileSync(path.join(dir, 'genome_kid.txt'), text(kid)); fs.writeFileSync(path.join(dir, 'phased_genotype_mix.txt'), '# phased\n' + text(mix, true));
  fs.writeFileSync(path.join(dir, 'genome_mix.txt'), text(mix));
  console.log(fails.length ? `\n${fails.length} failed` : '\nall passed');
  process.exit(fails.length ? 1 : 0);
})();
