const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const p = await (await b.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1280, height: 1100 } })).newPage();
  const cors = { 'access-control-allow-origin': '*' };
  await p.route('https://myvariant.info/**', r => r.fulfill({ headers: cors, json: { total: 2, hits: [{ _id: 'chr6:g.26093141G>C' }, { _id: 'chr6:g.26093141G>A', clinvar: { rcv: [{ clinical_significance: 'Pathogenic' }, { clinical_significance: 'Pathogenic' }, { clinical_significance: 'risk factor' }] }, gnomad_genome: { af: { af: 0.0326, af_afr: 0.0071, af_nfe: 0.0571, af_eas: 0.0002 } }, gwassnps: [{ trait: 'Hemochromatosis' }, { trait: 'Ferritin levels' }], cadd: { phred: 24.1 } }] } }));
  await p.route('https://rest.ensembl.org/**', r => r.fulfill({ headers: cors, json: { name: 'rs1800562', MAF: 0.0124, minor_allele: 'A', most_severe_consequence: 'missense_variant' } }));
  await p.route('https://bots.snpedia.com/**', r => r.fulfill({ headers: cors, json: { query: { pages: { '123': { pageid: 123, title: 'Rs1800562' } } } } }));
  await p.goto('http://localhost:8765/?start=dashboard&tab=explorer');
  await p.fill('input[type=search]', 'rs1800562'); await p.click('button[data-rs=rs1800562]');
  await p.click('role=switch'); await p.click('text=Look up this marker'); await p.waitForSelector('text=PharmGKB');
  const out = (await p.innerText('[aria-live=polite] >> nth=1')).replace(/\n+/g, ' | ');
  console.log(out.slice(200, 1400));
  console.log(/Pathogenic/.test(out) && /0\.033/.test(out) ? 'PASS second hit read' : 'FAIL second hit not read');
  console.log(/Lowest East Asian 0\.00020, highest European 0\.057/.test(out) ? 'PASS regional gnomAD' : 'FAIL regional gnomAD');
  console.log(/Hemochromatosis; Ferritin levels/.test(out) && /2 traits linked/.test(out) ? 'PASS GWAS Catalog' : 'FAIL GWAS Catalog');
  console.log(/Score 24\.1/.test(out) && /top 1%/.test(out) ? 'PASS CADD' : 'FAIL CADD');
  await p.screenshot({ path: '../shots/mock-lookup.png' });
  await b.close();
})();
