# Builds test files for the review fixes:
#  genome_Full_me.txt  male, Y J1 (M267), mt J1, Arabian lactase, G6PD A-, MEFV M694V carrier,
#                      M267 stored under an i-number with a no-call duplicate, CSV copy
#  genome_Full_xxdash.txt  female file whose Y rows are single '-' no-calls
import random, re
random.seed(7)
src = open('../src/data.js').read()
rows = re.findall(r"\['(\w+)','(\w+)',(\d+),", src[src.index('const SNP_DEF'):src.index('const EXTRA_IDS')])
CH = [str(i) for i in range(1, 23)] + ['X', 'Y', 'MT']
def filler(n, chrom, start):
    out = []
    for i in range(n):
        out.append((f'rs{start+i}', chrom, 1000 + i * 997, random.choice(['AA','AG','GG','CC','CT','TT'])))
    return out
def build(sex, calls, ydash=False):
    lines = ['# This data file generated by 23andMe at: test', '# rsid\tchromosome\tposition\tgenotype']
    n = 0
    for c in CH:
        k = 120 if c == 'MT' else 700 if c == 'Y' else 1600
        for r in filler(k, c, 200000 + n):
            g = r[3]
            if c in ('Y', 'MT'): g = g[0]
            if c == 'Y' and sex == 'XX': g = '-' if ydash else '--'
            if c == 'X' and sex == 'XY': g = g[0]
            lines.append('\t'.join(map(str, (r[0], r[1], r[2], g))))
        n += k
    for rs, c, p in rows:
        g = calls.get(rs)
        if g is None: continue
        if rs == 'rs9341313':
            lines.append(f'{rs}\t{c}\t{p}\t--')          # duplicate no-call under the rsid
            lines.append(f'i5000999\t{c}\t{p}\t{g}')     # real call under an i-number
            continue
        if rs.startswith('mt'): rs = 'i7012308'
        lines.append(f'{rs}\t{c}\t{p}\t{g}')
    return '\n'.join(lines) + '\n'
me = {
 'rs4988235':'GG','rs41380347':'AC','rs1050828':'T','rs5030868':'G','rs61752717':'TC','rs28940579':'AA','rs28940578':'CC','rs28940580':'CC',
 'rs429358':'TT','rs7412':'CC','rs4244285':'GG','rs4986893':'GA','rs12248560':'CC','rs4149056':'TT',
 'rs9786153':'T','rs34276300':'C','rs1236440':'C','rs17250535':'T','rs13447352':'C','rs9341313':'G','rs2032604':'T','rs2032654':'A','rs2032636':'G','rs9341296':'C',
 'rs2854128':'G','rs2015062':'T','rs3928306':'A','rs2853495':'A','rs1599988':'C','rs193302994':'A','rs2853826':'G','mt12308':'A'}
open('genome_Full_me.txt', 'w').write(build('XY', me))
open('genome_Full_me.csv', 'w').write('\n'.join(l if l.startswith('#') else ','.join(l.split('\t')) for l in build('XY', me).splitlines()) + '\n')
open('genome_Full_xxdash.txt', 'w').write(build('XX', {'rs2015062':'C','rs2854128':'A','rs3928306':'G'}, ydash=True))
