/* Builds genome_Full_mix.txt: a made-up man of mixed European and East Asian
   ancestry, used for the heritage tests and the README screenshots. No real person's
   DNA is in it. Each copy of each chromosome is drawn from the allele frequencies of
   reference groups (in blocks of 20 to 60 Mb when a copy mixes groups; set MIX to try
   others). The maternal line is H1 and the paternal line O-M122, written from the two
   trees, and the health markers come from the built-in sample person.
   Run: node tests/files/make_mixed.js */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..', '..');
const load = f => fs.readFileSync(path.join(root, f), 'utf8');
global.self = global; global.t = s => s;
eval(load('src/data.js') + load('src/ref.js') + load('src/anc.js') + ';Object.assign(global, { REF_PANEL, REF_MT, REF_Y, locusAnc, SAMPLE_GENOS, SNP_DEF })');

let seed = 2026; const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; };
const U = locusAnc().unpack(REF_PANEL), K = U.K;
const grp = id => REF_PANEL.groups.findIndex(g => g.id === id);
// One copy Northwestern European, the other Han Chinese, like a child of one parent from each.
const COPY = process.env.MIX ? JSON.parse(process.env.MIX) : [[['nwe', 1]], [['han', 1]]];
const pick = w => { let r = rnd(); for (const [g, p] of w) if ((r -= p) <= 0) return grp(g); return grp(w[0][0]); };
const out = [];
for (let c = 1; c <= 22; c++) {
  const idx = []; for (let i = 0; i < U.n; i++) if (U.chr[i] === c) idx.push(i);
  const hap = COPY.map(w => { let g = pick(w), end = 0; return idx.map(i => { if (U.pos[i] > end) { g = pick(w); end = U.pos[i] + (20 + 40 * rnd()) * 1e6; } return rnd() < U.F[i * K + g] ? U.alt[i] : U.ref[i]; }); });
  idx.forEach((i, j) => out.push([U.ids[i], c, U.pos[i], hap[0][j] + hap[1][j]]));
}
// Health and trait markers from the sample person (autosomes only; X and Y come below).
const panel = new Set(out.map(r => r[0]));
// Left out: the ABO deletion (an indel, which tests/formats.js cannot write in every layout)
// and two markers with no GRCh38 reference letter, so every format carries the same calls.
const SKIP = new Set(['rs8176719', 'rs4477212', 'rs35004220']);
SNP_DEF.forEach(([id, c, p]) => { const g = SAMPLE_GENOS[id]; if (g && /^\d+$/.test(c) && !panel.has(id) && !SKIP.has(id)) out.push([id, +c, p, g]); });
// Maternal line: walk the PhyloTree path to the chosen branch and write every tree position.
const N = REF_MT.nodes, tgt = N.findIndex(n => n[0] === 'H1'), prof = new Map();
const chain = []; for (let i = tgt; i >= 0; i = N[i][1]) chain.unshift(i);
chain.forEach(i => N[i][2].forEach(([p, a]) => { if (a === REF_MT.ref[p - 1]) prof.delete(p); else prof.set(p, a); }));
const mtPos = new Set(); N.forEach(n => n[2].forEach(x => mtPos.add(x[0])));
[...mtPos].sort((a, b) => a - b).forEach(p => out.push([`mt${p}`, 'MT', p, prof.get(p) || REF_MT.ref[p - 1]]));
// Paternal line: derived letters on the path to O-M122, ancestral elsewhere.
const Y = REF_Y, yN = Y.snp.length && Y.node[Y.snp.indexOf('M122')], onPath = new Set();
for (let k = yN; k >= 0; k = Y.par[k]) onPath.add(k);
const yp = Y.pos.split(',').map(Number); let p0 = 0;
// Like a chip, only part of the tree is read: every site on the path, the curated Y markers
// and about 2,600 others. A position shared by several tree branches is read only when it is on the path.
const ySite = new Map();
for (let i = 0; i < Y.node.length; i++) { p0 += yp[i]; const on = onPath.has(Y.node[i]); const prev = ySite.get(p0);
  ySite.set(p0, { on: on || (prev && prev.on), multi: !!prev, g: on ? Y.alle[2 * i + 1] : prev && prev.on ? prev.g : Y.alle[2 * i] }); }
const yCur = new Set(SNP_DEF.filter(r => r[1] === 'Y').map(r => r[2]));
for (const [p, v] of ySite) if (v.on || yCur.has(p) || (!v.multi && rnd() < 0.17)) out.push([`y${p}`, 'Y', p, v.g]);
// Name the rows that are curated markers by their rsid, so other test files that carry
// the same marker (tests/formats.js merges one in) do not add a second, different call.
const NAME = {}; SNP_DEF.forEach(([id, c, p]) => { if (c === 'Y' || c === 'MT') NAME[c + ':' + p] = id; });
out.forEach(r => { const id = NAME[r[1] + ':' + r[2]]; if (id) r[0] = id; });
const order = c => c === 'MT' ? 25 : c === 'Y' ? 24 : +c;
out.sort((a, b) => order(a[1]) - order(b[1]) || a[2] - b[2]);
fs.writeFileSync(path.join(__dirname, 'genome_Full_mix.txt'), '# This data file generated by 23andMe at: test\n# Made-up person for testing; not real DNA.\n# rsid\tchromosome\tposition\tgenotype\n' + out.map(r => r.join('\t')).join('\n') + '\n');
console.log('wrote', out.length, 'rows');
