"""Builds src/b38.js: what LiberateDNA needs to read files on other genome builds
and to fill in reference calls from whole genome VCF files.

Inputs (in ../anc, fetched by tools in that folder):
  cand2.json                     GSA markers with GRCh37 and GRCh38 positions
  grch37_to_grch38.over.chain.gz liftOver chain (UCSC)
and the gnomAD v3.1.2 HGDP + 1000 Genomes VCFs (read by range requests) for the
reference letter at each curated marker.
"""
import json, os, re, sys
from pyliftover import LiftOver
here = os.path.dirname(os.path.abspath(__file__))
A = os.environ.get('ANC', os.path.join(here, '..', 'anc'))
lo = LiftOver(os.path.join(A, 'grch37_to_grch38.over.chain.gz'))

src = open(os.path.join(here, 'ref.js')).read()
def const(name): return json.loads(re.search(r'const ' + name + r' = (.*?);\n', src, re.S).group(1))
P, Y = const('REF_PANEL'), const('REF_Y')

def b36(x):
    n = 0
    for ch in x: n = n * 36 + int(ch, 36)
    return n
ids = ['rs' + str(int(x, 36)) for x in P['rs'].split(',')]
p38 = {r[3]: r[2] for r in json.load(open(os.path.join(A, 'cand2.json')))}
chrs = list(__import__('base64').b64decode(P['chr']))
dp = list(map(int, P['dpos'].split(','))); pos = []; last = 0; lc = -1
for c, d in zip(chrs, dp):
    if c != lc: last = 0; lc = c
    last += d; pos.append(last)

def lift(c, p):
    m = lo.convert_coordinate(c, p - 1)
    if not m or len(m) != 1 or m[0][0] != 'chr' + c: return None
    return m[0][1] + 1

def rle(offs):
    # Shift from GRCh37 to GRCh38 for each site, run-length coded: "shift*count".
    out = []; prev = None; n = 0
    for o in offs:
        if o == prev: n += 1
        else:
            if prev is not None: out.append(f'{prev}*{n}' if n > 1 else str(prev))
            prev, n = o, 1
    out.append(f'{prev}*{n}' if n > 1 else str(prev))
    return ','.join(out)

def chname(c): return {23: 'X', 24: 'Y', 25: 'MT'}.get(c, str(c))
po = []
for i, (c, p) in enumerate(zip(chrs, pos)):
    q = p38.get(ids[i]) or lift(chname(c), p)
    po.append('x' if q is None else q - p)
yp = []; last = 0
for d in map(int, Y['pos'].split(',')):
    last += d; q = lift('Y', last); yp.append('x' if q is None else q - last)

# Curated markers: GRCh38 position and the reference letter (for whole genome VCFs,
# where a site that matches the reference is not listed).
data = open(os.path.join(here, 'data.js')).read()
rows = re.findall(r"\['(rs\d+|i\d+)','(\w+)',(\d+),", data)
import pysam
URL = 'https://storage.googleapis.com/gcp-public-data--gnomad/release/3.1.2/vcf/genomes/gnomad.genomes.v3.1.2.hgdp_tgp.chr{}.vcf.bgz'
tb = {}
cur = {}
for rid, c, p in rows:
    p = int(p)
    if c == 'MT': continue
    q = lift(c, p)
    if q is None: print('no lift', rid, file=sys.stderr); continue
    ref = ''
    try:
        if c not in tb: tb[c] = pysam.TabixFile(URL.format(c))
        for r in tb[c].fetch('chr' + c, q - 1, q):
            f = r.split('\t', 5)
            if int(f[1]) == q and len(f[3]) == 1: ref = f[3]; break
    except Exception as e: print('fetch', rid, e, file=sys.stderr)
    cur[rid] = [q, ref]
print('panel lifted', sum(1 for o in po if o != 'x'), 'of', len(po), '| y', sum(1 for o in yp if o != 'x'), 'of', len(yp),
      '| curated', len(cur), 'with ref', sum(1 for v in cur.values() if v[1]), file=sys.stderr)
out = {'panel': rle(po), 'y': rle(yp), 'cur': cur}
open(os.path.join(here, 'b38.js'), 'w').write(
    '/* Generated by b38build.py from the UCSC liftOver chain (GRCh37 to GRCh38) and gnomAD v3.1.2. */\n'
    'const REF_B38 = ' + json.dumps(out, separators=(',', ':')) + ';\n')
